### PR TITLE
Add a basic beginning of how the frame can support the arms 'n' shit

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**

### CODE REVIEW

**Review by IamfromSpace — COMMENTED** [review]
Might want to add a comment to this line as to what it does, so we remember why it was there :)

**Comment by MichaelRFairhurst** [comment]
Ha, yes!

**Comment by MichaelRFairhurst** [comment]
Ha, yes!

**Comment by MichaelRFairhurst** [comment]
Closing, this was used to make #21 and aint needed no mo

**Pull request closed without merging**
